/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OligarkiRouteImport } from './routes/_oligarki'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AnsActivityRouteImport } from './routes/ans/activity'
import { Route as OligarkiDashboardRouteRouteImport } from './routes/_oligarki/dashboard/route'

const OligarkiRoute = OligarkiRouteImport.update({
  id: '/_oligarki',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnsActivityRoute = AnsActivityRouteImport.update({
  id: '/ans/activity',
  path: '/ans/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const OligarkiDashboardRouteRoute = OligarkiDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OligarkiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof OligarkiDashboardRouteRoute
  '/ans/activity': typeof AnsActivityRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof OligarkiDashboardRouteRoute
  '/ans/activity': typeof AnsActivityRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_oligarki': typeof OligarkiRouteWithChildren
  '/_oligarki/dashboard': typeof OligarkiDashboardRouteRoute
  '/ans/activity': typeof AnsActivityRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/ans/activity' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/ans/activity' | '/login'
  id:
    | '__root__'
    | '/'
    | '/_oligarki'
    | '/_oligarki/dashboard'
    | '/ans/activity'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OligarkiRoute: typeof OligarkiRouteWithChildren
  AnsActivityRoute: typeof AnsActivityRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_oligarki': {
      id: '/_oligarki'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OligarkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ans/activity': {
      id: '/ans/activity'
      path: '/ans/activity'
      fullPath: '/ans/activity'
      preLoaderRoute: typeof AnsActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_oligarki/dashboard': {
      id: '/_oligarki/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof OligarkiDashboardRouteRouteImport
      parentRoute: typeof OligarkiRoute
    }
  }
}

interface OligarkiRouteChildren {
  OligarkiDashboardRouteRoute: typeof OligarkiDashboardRouteRoute
}

const OligarkiRouteChildren: OligarkiRouteChildren = {
  OligarkiDashboardRouteRoute: OligarkiDashboardRouteRoute,
}

const OligarkiRouteWithChildren = OligarkiRoute._addFileChildren(
  OligarkiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OligarkiRoute: OligarkiRouteWithChildren,
  AnsActivityRoute: AnsActivityRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
